const words = [
	{
		label: 'Приветствие',
		keys: ['здравствуйте', 'добрый вечер', 'доброе утро'],
		selected: false,
		score: 4500,
		voc: true,
	},
	{
		label: 'Прощание',
		keys: ['до свидания', 'всего доброго'],
		selected: false,
		score: 4500,
		voc: true,
	},
	{ label: 'здравствуйте', key: 'здравствуйте', score: 4000, selected: false, part: 'adv' },
	{ label: 'добрый вечер', key: 'добрый вечер', score: 3990, selected: false, part: 'adv' },
	{ label: 'доброе утро', key: 'доброе утро', score: 3995, selected: false, part: 'adv' },
	{ label: 'до свидания', key: 'до свидания', score: 3500, selected: false, part: 'adv' },
	{
		label: 'спасибо за ожидание',
		key: 'спасибо за ожидание',
		score: 3400,
		selected: false,
		part: 'f',
	},
	{ label: 'всего доброго', key: 'всего доброго', score: 3400, selected: false, part: 'adv' },
	{ label: 'претензия', key: 'претензия', score: 3000, selected: false, part: 's' },
	{ label: 'сим-карта', key: 'сим-карта', score: 2900, selected: false, part: 's' },
	{ label: 'поменялся номер', key: 'поменялся номер', score: 2700, selected: false, part: 'f' },
	{
		label: 'оставайтесь на линии',
		key: 'оставайтесь на линии',
		score: 2600,
		selected: false,
		part: 'f',
	},
	{ label: 'сказать', key: 'сказать', score: 2396.6, selected: false, part: 'v' },
	{ label: 'время', key: 'время', score: 2015.7, selected: false, part: 's' },
	{ label: 'говорить', key: 'говорить', score: 1755.0, selected: false, part: 'v' },
	{ label: 'знать', key: 'знать', score: 1713.8, selected: false, part: 'v' },
	{ label: 'стать', key: 'стать', score: 1621.8, selected: false, part: 'v' },
	{ label: 'дело', key: 'дело', score: 1412.1, selected: false, part: 's' },
	{ label: 'жизнь', key: 'жизнь', score: 1389.8, selected: false, part: 's' },
	{ label: 'очень', key: 'очень', score: 1286.8, selected: false, part: 'adv' },
	{ label: 'день', key: 'день', score: 1258.4, selected: false, part: 's' },
	{ label: 'новый', key: 'новый', score: 1217.5, selected: false, part: 'a' },
	{ label: 'рука', key: 'рука', score: 1200.6, selected: false, part: 's' },
	{ label: 'работа', key: 'работа', score: 1058.3, selected: false, part: 's' },
	{ label: 'надо', key: 'надо', score: 993.2, selected: false, part: 'adv' },
	{ label: 'хотеть', key: 'хотеть', score: 991.3, selected: false, part: 'v' },
	{ label: 'слово', key: 'слово', score: 967.9, selected: false, part: 's' },
	{ label: 'идти', key: 'идти', score: 957.1, selected: false, part: 'v' },
	{ label: 'большой', key: 'большой', score: 944.4, selected: false, part: 'a' },
	{ label: 'должен', key: 'должен', score: 944.2, selected: false, part: 'a' },
	{ label: 'место', key: 'место', score: 926.6, selected: false, part: 's' },
	{ label: 'иметь', key: 'иметь', score: 906.7, selected: false, part: 'v' },
	{ label: 'лицо', key: 'лицо', score: 878.0, selected: false, part: 's' },
	{ label: 'друг', key: 'друг', score: 874.2, selected: false, part: 's' },
	{ label: 'нет', key: 'нет', score: 874.0, selected: false, part: 'adv' },
	{ label: 'глаз', key: 'глаз', score: 857.6, selected: false, part: 's' },
	{ label: 'тоже', key: 'тоже', score: 841.5, selected: false, part: 'adv' },
	{ label: 'видеть', key: 'видеть', score: 818.2, selected: false, part: 'v' },
	{ label: 'вопрос', key: 'вопрос', score: 805.8, selected: false, part: 's' },
	{ label: 'дом', key: 'дом', score: 792.6, selected: false, part: 's' },
	{ label: 'сторона', key: 'сторона', score: 768.3, selected: false, part: 's' },
	{ label: 'думать', key: 'думать', score: 755.5, selected: false, part: 'v' },
	{ label: 'сделать', key: 'сделать', score: 743.5, selected: false, part: 'v' },
	{ label: 'страна', key: 'страна', score: 725.7, selected: false, part: 's' },
	{ label: 'жить', key: 'жить', score: 725.5, selected: false, part: 'v' },
	{ label: 'мир', key: 'мир', score: 714.7, selected: false, part: 's' },
	{ label: 'последний', key: 'последний', score: 712.6, selected: false, part: 'a' },
	{ label: 'случай', key: 'случай', score: 709.7, selected: false, part: 's' },
	{ label: 'голова', key: 'голова', score: 709.4, selected: false, part: 's' },
	{ label: 'более', key: 'более', score: 706.2, selected: false, part: 'adv' },
	{ label: 'делать', key: 'делать', score: 701.1, selected: false, part: 'v' },
	{ label: 'смотреть', key: 'смотреть', score: 667.2, selected: false, part: 'v' },
	{ label: 'ребенок', key: 'ребенок', score: 658.3, selected: false, part: 's' },
	{ label: 'конечно', key: 'конечно', score: 647.3, selected: false, part: 'adv' },
	{ label: 'сила', key: 'сила', score: 645.8, selected: false, part: 's' },
	{ label: 'российский', key: 'российский', score: 644.6, selected: false, part: 'a' },
	{ label: 'конец', key: 'конец', score: 634.7, selected: false, part: 's' },
	{ label: 'вид', key: 'вид', score: 620.1, selected: false, part: 's' },
	{ label: 'система', key: 'система', score: 617.8, selected: false, part: 's' },
	{ label: 'работать', key: 'работать', score: 611.2, selected: false, part: 'v' },
	{ label: 'понять', key: 'понять', score: 588.2, selected: false, part: 'v' },
	{ label: 'пойти', key: 'пойти', score: 587.2, selected: false, part: 'v' },
	{ label: 'часть', key: 'часть', score: 585.4, selected: false, part: 's' },
	{ label: 'спросить', key: 'спросить', score: 573.9, selected: false, part: 'v' },
	{ label: 'город', key: 'город', score: 573.4, selected: false, part: 's' },
	{ label: 'дать', key: 'дать', score: 573.1, selected: false, part: 'v' },
	{ label: 'также', key: 'также', score: 569.9, selected: false, part: 'adv' },
	{ label: 'понимать', key: 'понимать', score: 559.7, selected: false, part: 'v' },
	{ label: 'получить', key: 'получить', score: 557.7, selected: false, part: 'v' },
	{ label: 'отношение', key: 'отношение', score: 557.4, selected: false, part: 's' },
	{ label: 'сидеть', key: 'сидеть', score: 538.1, selected: false, part: 'v' },
	{ label: 'женщина', key: 'женщина', score: 533.3, selected: false, part: 's' },
	{ label: 'оказаться', key: 'оказаться', score: 531.9, selected: false, part: 'v' },
	{ label: 'русский', key: 'русский', score: 530.5, selected: false, part: 'a' },
	{ label: 'взять', key: 'взять', score: 525.8, selected: false, part: 'v' },
	{ label: 'прийти', key: 'прийти', score: 523.3, selected: false, part: 'v' },
	{ label: 'являться', key: 'являться', score: 522.9, selected: false, part: 'v' },
	{ label: 'деньги', key: 'деньги', score: 512.4, selected: false, part: 's' },
	{ label: 'вдруг', key: 'вдруг', score: 503.2, selected: false, part: 'adv' },
	{ label: 'любить', key: 'любить', score: 503.1, selected: false, part: 'v' },
	{ label: 'стоить', key: 'стоить', score: 501.9, selected: false, part: 'v' },
	{ label: 'почти', key: 'почти', score: 501.7, selected: false, part: 'adv' },
	{ label: 'земля', key: 'земля', score: 494.4, selected: false, part: 's' },
	{ label: 'общий', key: 'общий', score: 492.4, selected: false, part: 'a' },
	{ label: 'машина', key: 'машина', score: 490.4, selected: false, part: 's' },
	{ label: 'сразу', key: 'сразу', score: 486.0, selected: false, part: 'adv' },
	{ label: 'хорошо', key: 'хорошо', score: 485.7, selected: false, part: 'adv' },
	{ label: 'вода', key: 'вода', score: 484.8, selected: false, part: 's' },
	{ label: 'отец', key: 'отец', score: 484.1, selected: false, part: 's' },
	{ label: 'высокий', key: 'высокий', score: 483.3, selected: false, part: 'a' },
	{ label: 'остаться', key: 'остаться', score: 482.7, selected: false, part: 'v' },
	{ label: 'выйти', key: 'выйти', score: 480.9, selected: false, part: 'v' },
	{ label: 'проблема', key: 'проблема', score: 474.9, selected: false, part: 's' },
	{ label: 'начать', key: 'начать', score: 473.3, selected: false, part: 'v' },
	{ label: 'хороший', key: 'хороший', score: 471.4, selected: false, part: 'a' },
	{ label: 'час', key: 'час', score: 468.1, selected: false, part: 's' },
	{ label: 'сегодня', key: 'сегодня', score: 463.5, selected: false, part: 'adv' },
	{ label: 'право', key: 'право', score: 461.4, selected: false, part: 's' },
	{ label: 'совсем', key: 'совсем', score: 460.5, selected: false, part: 'adv' },
	{ label: 'нога', key: 'нога', score: 459.2, selected: false, part: 's' },
	{ label: 'считать', key: 'считать', score: 455.3, selected: false, part: 'v' },
	{ label: 'главный', key: 'главный', score: 454.6, selected: false, part: 'a' },
	{ label: 'решение', key: 'решение', score: 453.4, selected: false, part: 's' },
	{ label: 'увидеть', key: 'увидеть', score: 452.4, selected: false, part: 'v' },
	{ label: 'дверь', key: 'дверь', score: 450.8, selected: false, part: 's' },
	{ label: 'казаться', key: 'казаться', score: 448.2, selected: false, part: 'v' },
	{ label: 'образ', key: 'образ', score: 445.9, selected: false, part: 's' },
	{ label: 'писать', key: 'писать', score: 444.3, selected: false, part: 'v' },
	{ label: 'история', key: 'история', score: 443.9, selected: false, part: 's' },
	{ label: 'лучший', key: 'лучший', score: 443.2, selected: false, part: 'a' },
	{ label: 'власть', key: 'власть', score: 435.6, selected: false, part: 's' },
	{ label: 'закон', key: 'закон', score: 433.4, selected: false, part: 's' },
	{ label: 'война', key: 'война', score: 425.9, selected: false, part: 's' },
	{ label: 'бог', key: 'бог', score: 425.4, selected: false, part: 's' },
	{ label: 'голос', key: 'голос', score: 424.5, selected: false, part: 's' },
	{ label: 'найти', key: 'найти', score: 424.1, selected: false, part: 'v' },
]

const vocabs = [
	{ name: 'Приветствие', keys: ['здравствуйте', 'добрый вечер', 'доброе утро'], selected: false },
	{ name: 'Прощание', keys: ['до свидания', 'всего доброго'], selected: false },
]

export { words, vocabs }
