const notifications = [
	{ id: 31, name: 'друг', channel: 'все', date: 'сегодня', unread: true, old: false },
	{ id: 13, name: 'знать', channel: 'клиент', date: 'сегодня', unread: true, old: false },
	{ id: 3, name: 'до свидания', channel: 'оператор', date: 'сегодня', unread: false, old: false },
	{ id: 14, name: 'стать', channel: 'клиент', date: 'вчера', unread: true, old: false },
	{ id: 8, name: 'поменялся номер', channel: 'оператор', date: 'вчера', unread: true, old: false },
	{ id: 19, name: 'новый', channel: 'клиент', date: 'вчера', unread: true, old: true },
	{
		id: 9,
		name: 'оставайтесь на линии',
		channel: 'оператор',
		date: 'вчера',
		unread: false,
		old: true,
	},
	{ id: 23, name: 'хотеть', channel: 'клиент', date: 'вчера', unread: true, old: true },
	{ id: 34, name: 'тоже', channel: 'все', date: '2022-05-29', unread: false, old: true },
	{ id: 28, name: 'место', channel: 'все', date: '2022-05-29', unread: false, old: true },
	{ id: 10, name: 'сказать', channel: 'оператор', date: '2022-05-29', unread: true, old: true },
	{ id: 37, name: 'нормально', channel: 'все', date: '2022-05-29', unread: false, old: true },
	{ id: 26, name: 'большой', channel: 'все', date: '2022-05-28', unread: false, old: true },
	{ id: 22, name: 'надо', channel: 'клиент', date: '2022-05-28', unread: false, old: true },
	{ id: 24, name: 'слово', channel: 'клиент', date: '2022-05-28', unread: false, old: true },
	{ id: 18, name: 'день', channel: 'клиент', date: '2022-05-28', unread: false, old: true },
	{ id: 15, name: 'дело', channel: 'клиент', date: '2022-05-28', unread: false, old: true },
	{ id: 36, name: 'слышать', channel: 'все', date: '2022-05-28', unread: false, old: true },
	{ id: 17, name: 'очень', channel: 'клиент', date: '2022-05-28', unread: false, old: true },
	{ id: 27, name: 'должен', channel: 'все', date: '2022-05-26', unread: false, old: true },
	{
		id: 5,
		name: 'всего доброго',
		channel: 'оператор',
		date: '2022-05-26',
		unread: false,
		old: true,
	},
	{ id: 2, name: 'доброе утро', channel: 'оператор', date: '2022-05-26', unread: false, old: true },
	{ id: 11, name: 'время', channel: 'клиент', date: '2022-05-26', unread: false, old: true },
	{ id: 33, name: 'глаз', channel: 'все', date: '2022-05-26', unread: false, old: true },
	{ id: 25, name: 'идти', channel: 'все', date: '2022-05-26', unread: false, old: true },
	{ id: 20, name: 'рука', channel: 'клиент', date: '2022-05-26', unread: false, old: true },
	{ id: 30, name: 'лицо', channel: 'все', date: '2022-05-26', unread: false, old: true },
	{ id: 21, name: 'работа', channel: 'клиент', date: '2022-05-26', unread: false, old: true },
	{ id: 16, name: 'жизнь', channel: 'клиент', date: '2022-05-26', unread: false, old: true },
	{ id: 29, name: 'иметь', channel: 'все', date: '2022-05-26', unread: false, old: true },
	{
		id: 1,
		name: 'добрый вечер',
		channel: 'оператор',
		date: '2022-05-26',
		unread: false,
		old: true,
	},
	{ id: 32, name: 'нет', channel: 'все', date: '2022-05-23', unread: false, old: true },
	{ id: 12, name: 'говорить', channel: 'клиент', date: '2022-05-23', unread: false, old: true },
	{
		id: 4,
		name: 'спасибо за ожидание ',
		channel: 'оператор',
		date: '2022-05-23',
		unread: false,
		old: true,
	},
	{ id: 7, name: 'сим-карта', channel: 'оператор', date: '2022-05-23', unread: false, old: true },
	{
		id: 0,
		name: 'здравствуйте',
		channel: 'оператор',
		date: '2022-05-23',
		unread: false,
		old: true,
	},
	{ id: 6, name: 'претензия', channel: 'оператор', date: '2022-05-23', unread: false, old: true },
]

export { notifications }
